### ISSUE TITLE
Compatibility with latest human GEM

### ISSUE THREAD

**Issue by Yu-sysbio** [CompBioLj/COVID_GEMs_and_MEMs#1]
Hi, I would like to reproduce the study of evaluating various MEMs using the latest version of human GEM v1.11.0. It seems that the gene list has been changed from v1.6.0 (which was used in the original study) to the latest one, and therefore the TPM files (e.g., [A549_Healthy_mean.mat](https://github.com/CompBioLj/COVID_GEMs_and_MEMs/blob/main/Code/Matlab/A549_Healthy_mean.mat)) cannot be used. I am wondering if it is possible that the TPM values for all genes (currently only for the genes included in v1.6.0) could be uploaded. I would also appreciate any suggestions.

**Comment by mmoskon** [comment]
Hi, 

I am sorry, but I don't have these files on my computer. The person who was responsible for this part of the analysis is unfurtunately not working with us any longer. I have contacted them and I will let you know when/if they respond.

Best wishes,
Miha
